language:
- python

cache:
- pip

python:
- "3.5"

install:
- pip install coverage
- pip install coveralls
- pip install pytest-cov
- pip install -r requirements.txt

services:
- postgresql

before_script:
- psql -c "CREATE ROLE arthuroe PASSWORD 'dbadmin' CREATEDB CREATEROLE INHERIT LOGIN;" -U postgres
- psql -c "create database shoppinglist;" -U postgres


script:
- pytest --cov tests

after_success:
- coverage report
- coveralls

 notifications:
    slack:
      secure: XpQWSI1UREV/7mfvW7vgR638lRWzItMVHVOUbkmcJlg6BSNREiO5dX0xDxXqBKy3kgowwkWaK0zp2SbZ2H2kO7wBONq740UxwY4CA7T1H+AeQWC6S+Oc3JhH6N3bj0daX3tU/YWZMeOOu+6+nJ9DskVJvmI8OvBkBmWDOlbfAK2io0m+UFzi4BsfTSw7NQXp8YQEkgJo5jOyJ5rvyV6E/E9VIp5UpW0TdvaY91x6RDFLn3LMh02Evt1MOGm4Nu3UpZ65AvaBefCrefSsNeO3CQnANk6A4D2FI4LtqxCbmckulIDHXF4vCLDUtDS/i+Wu6L0gTYtfOKUTT8UaOmH3WjPbiD8ifjGhYIudz2r8+6dLINrmVdTkHCsCQz3PZUy9y4RK5TiUmpYvPIZSuLRSleJhRSSbN68JLHDaQCXSHEvRDAN1zCgR8iGa5L7BOdWlcogjFupBV8DP3vDAcyuf+VVfrWDQ29Zx/aigUTl6NDzvif+8X2+DUchJAfBTYahawhHbv7URZc3BfM7dt5JEzMUf9OMNlHkytneoFc0PBXFhRKCskQIlU61oVNhzK9c5QUjCLsG2vR0pouU4/+tQP60EeP6iPT5cuDZVQLu3DLmRX7z02ybIifkIbJY53wrOuz73raCB7AgTr81/fcPaYkMSObvZ4zzuz/oO+ezYLVM=
